using System;
using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ContentTypeTextNet.Pe.Generator
{
    public class SourceBuilder
    {
        #region property

        public string Header => "// <auto-generated/>";

        #endregion

        #region function

        public string ToCode<T>(T target)
            where T : Enum
        {
            var type = target.GetType();
            return "global::" + type.FullName + "." + target.ToString();
        }

        public string ToCode<T>()
        {
            var type = typeof(T);
            return "global::" + type.FullName;
        }

        public string ToNamespaceCode(INamedTypeSymbol targetSymbol)
        {
            return targetSymbol.ContainingNamespace.IsGlobalNamespace ?
                "" :
                "namespace " + targetSymbol.ContainingNamespace + ";"
            ;
        }

        public string ToSourceFilePath(INamedTypeSymbol targetSymbol)
        {
            var targetName = targetSymbol.Name;
            var fullName = (targetSymbol.ContainingNamespace.IsGlobalNamespace ? "" : targetSymbol.ContainingNamespace + ".") + targetName;
            return $"{fullName}.g.cs";
        }

        #endregion
    }
}
