version: '{build}'
image: Visual Studio 2019 Preview
skip_tags: true
clone_depth: 1
install:
  - cmd: choco install dotnetcore-sdk --version 3.0.100-preview9-014004
  - cmd: dotnet --version
before_build:
  - cmd: git submodule init
  - cmd: git submodule update
build_script:
  - cmd: dotnet build Source/Pe/Pe.sln --verbosity normal --configuration Release --runtime win-x64
test_script:
  - cmd: dotnet test Source/Pe/Pe.sln --verbosity normal --no-build --configuration Release --runtime win-x64
artifacts:
- path: Output\
