version: '{build}'
image: Visual Studio 2019
skip_tags: true
clone_depth: 1
environment:
  CI: HAGE
  BUILD_TYPE: BETA
  BUILD_OUTPUT: FULL
branches:
  except:
    - master
install:
  - cmd: dotnet --version
  - cmd: choco install dotnetcore-sdk --version 3.0.100
  - cmd: dotnet --version
before_build:
  - cmd: git submodule init
  - cmd: git submodule update
build_script:
  - cmd: dotnet build   Source/Pe/Pe.sln --verbosity normal --configuration Release --runtime win-x64
  - cmd: dotnet publish Source/Pe/Pe/Pe.csproj --verbosity normal --configuration Release --runtime win-x64 --output Output/Release/x64/Pe --self-contained true
before_test:
  - cmd: cd Source\Pe\Pe.Core.Test
  - cmd: nuget install Appveyor.TestLogger -Version 2.0.0
  - cmd: cd ..\..\..\
  - cmd: cd Source\Pe\Pe.Test
  - cmd: nuget install Appveyor.TestLogger -Version 2.0.0
  - cmd: cd ..\..\..\
test_script:
  - cmd: dotnet test Source/Pe/Pe.sln --verbosity normal --no-build --no-restore --configuration Release --runtime win-x64 --test-adapter-path:. --logger:Appveyor
artifacts:
- path: Output\
cache:
 - '%LOCALAPPDATA%\NuGet'
 - '%USERPROFILE%\.nuget'
 - C:\ProgramData\chocolatey\bin -> appveyor.yml
 - C:\ProgramData\chocolatey\lib -> appveyor.yml
