version: '{build}'
image: Visual Studio 2019
skip_tags: true
clone_depth: 1
environment:
  BUILD_TYPE:
  ARCHIVE: 7z
branches:
  only:
    - master
    - ci-test
install:
  - cmd: dotnet --version
  #- cmd: choco install dotnetcore-sdk --version 3.1.100
  #- cmd: dotnet --version
  - ps: Install-Product node 12.14.1
  - cmd: npm --version
  #- cmd: npm -g install npm@6.13.4
  - cmd: set
before_build:
  - cmd: git submodule init
  - cmd: git submodule update
build_script:
  - ps: .\Build\build.ps1 -ProductMode -Platform x64 -BuildType ""
  # - ps: .\Build\build.ps1 -ProductMode -Platform x86 -BuildType ""
  - ps: .\Build\create-document.ps1 -Platform x64
  # - ps: .\Build\create-document.ps1 -Platform x86
  - ps: .\Build\compress.ps1 -SourceDirectory Output\Release\x64\Pe -DestinationDirectory Output -Platform x64 -Diet -Archive $env:ARCHIVE
  # - ps: .\Build\compress.ps1 -SourceDirectory Output\Release\x86\Pe -DestinationDirectory Output -Platform x86 -Diet -Archive $env:ARCHIVE
  # - ps: .\Build\create-updateinfo.ps1 -TargetRepository bitbucket -MinimumVersion 0.83.0 -ArchiveBaseUrl $env:PE_RELEASE_ARCHIVE_BASE_URL -NoteBaseUrl $env:PE_RELEASE_NOTE_BASE_URL -ReleaseDirectory Output -Archive $env:ARCHIVE -Platforms x64,x86
  - ps: .\Build\create-updateinfo.ps1 -TargetRepository bitbucket -MinimumVersion 0.83.0 -ArchiveBaseUrl $env:PE_RELEASE_ARCHIVE_BASE_URL -NoteBaseUrl $env:PE_RELEASE_NOTE_BASE_URL -ReleaseDirectory Output -Archive $env:ARCHIVE -Platforms x64
  - ps: .\Build\create-release-note.ps1
# before_test:
#   - cmd: for /d %%f in (Source\Pe\*.Test) do ( cd %%f & nuget install Appveyor.TestLogger -Version 2.0.0 & cd ..\..\..\ )
# test_script:
#   - cmd: dotnet test Source/Pe/Pe.sln --verbosity normal --no-build --no-restore --configuration Release --runtime win-x64 /p:Platform=x64 /p:DefineConstants="" --test-adapter-path:. --logger:Appveyor
#   - cmd: dotnet test Source/Pe/Pe.sln --verbosity normal --no-build --no-restore --configuration Release --runtime win-x86 /p:Platform=x86 /p:DefineConstants="" --test-adapter-path:. --logger:Appveyor
artifacts:
  - path: Output\*.json
  - path: Output\*.html
deploy_script:
  - ps: .\Build\deploy.ps1 -TargetRepository bitbucket -Archive $env:ARCHIVE -DeployApiDownloadUrl $env:PE_API_DOWNLOAD_URL -DeployApiTagUrl $env:PE_API_TAG_URL -DeployAccount $env:PE_RELEASE_ACCOUNT -DeployPassword $env:PE_RELEASE_PASSWORD
cache:
  - 'Source\Documents\node_modules'
