version: '{build}'
image: Visual Studio 2019
skip_tags: true
skip_commits:
  message: /^init/
clone_depth: 1
environment:
  BUILD_TYPE: BETA
  MAIN_ARCHIVE: tar
  DEFAULT_ARCHIVE: 7z
  MINIMUM_VERSION: 0.00.0
  NUGET_PACKAGES: C:\nuget
platform:
  - x64
  - x86
branches:
  except:
    - master
    - development
    - ci-test
install:
  - ps: . .\Build\appveyor\env-changer.ps1
  - cmd: dotnet --version
  #- cmd: choco install dotnetcore-sdk
  #- cmd: dotnet --version
  - ps: Install-Product node 15.6.0
  - cmd: npm -g install npm@7.4.0
  - cmd: npm install
before_build:
  - cmd: git submodule init
  - cmd: git submodule update
  - ps: .\Build\make-buildtools.ps1
build_script:
  - cmd: npm run help-ci
  - ps: .\Build\build.ps1 -ProductMode -IgnoreChanged -BuildType $env:BUILD_TYPE -Platforms $env:PLATFORM
  # - ps: .\Build\build.ps1 -IgnoreChanged -BuildType $env:BUILD_TYPE -Platforms $env:PLATFORM
before_test:
  - cmd: for /d %%d in (Source\Pe\*.Test) do ( cd %%d & nuget install Appveyor.TestLogger & cd ..\..\..\ )
test_script:
  - ps: .\Build\test.ps1 -MainConfigurations Release -BootConfigurations Release,CI_TEST -Logger Appveyor -Platforms $env:PLATFORM
after_test:
  - ps: .\Build\compress.ps1 -MainArchive $env:MAIN_ARCHIVE -DefaultArchive $env:DEFAULT_ARCHIVE -Platforms $env:PLATFORM
  - ps: .\Build\create-updateinfo.ps1 -TargetRepository bitbucket -MinimumVersion $env:MINIMUM_VERSION -ArchiveBaseUrl https://example.com -NoteBaseUrl https://example.net -ReleaseDirectory Output -MainArchive $env:MAIN_ARCHIVE -DefaultArchive $env:DEFAULT_ARCHIVE -Platforms $env:PLATFORM
  - cmd: git config --global core.quotepath "false"
  - ps: .\Build\create-release-note.ps1
artifacts:
  - path: Output\*.zip
  - path: Output\*.7z
  - path: Output\*.json
  - path: Output\*.html
  - path: Output\help
    name: document
cache:
  #- '%USERPROFILE%\.nuget\packages'
  - 'node_modules'
  # - 'C:\nuget'
  #- C:\ProgramData\chocolatey\bin -> appveyor.yml
  #- C:\ProgramData\chocolatey\lib -> appveyor.yml
