version: '{build}'
image: Visual Studio 2019
skip_tags: true
clone_depth: 1
branches:
  only:
    - pipeline
install:
  - cmd: dotnet --version
  #- cmd: choco install dotnetcore-sdk --version 3.1.100
  #- cmd: dotnet --version
  - cmd: set
before_build:
  - cmd: git submodule init
  - cmd: git submodule update
build_script:
  - ps: .\Build\build.ps1 -platform x64 -buildType ""
  - ps: .\Build\build.ps1 -platform x86 -buildType ""
  - ps: .\Build\compress.ps1 -SourceDirectory Output\Release\x64\Pe -DestinationDirectory Output -Platform x64
  - ps: .\Build\compress.ps1 -SourceDirectory Output\Release\x86\Pe -DestinationDirectory Output -Platform x86
before_test:
  - cmd: for /d %%f in (Source\Pe\*.Test) do ( cd %%f & nuget install Appveyor.TestLogger -Version 2.0.0 & cd ..\..\..\ )
test_script:
  - cmd: dotnet test Source/Pe/Pe.sln --verbosity normal --no-build --no-restore --configuration Release --runtime win-x64 /p:Platform=x64 /p:DefineConstants="" --test-adapter-path:. --logger:Appveyor
  - cmd: dotnet test Source/Pe/Pe.sln --verbosity normal --no-build --no-restore --configuration Release --runtime win-x86 /p:Platform=x86 /p:DefineConstants="" --test-adapter-path:. --logger:Appveyor
artifacts:
- path: Output\*.zip
deploy_script:
  - cmd: for %%A in ( Output\Release\*.zip ) do curl --user %PE_RELEASE_USER%:%PE_RELEASE_PASSWORD% -X POST %PE_DEPLOY_URL% -F files=@%%A

