version: '{build}'
image: Visual Studio 2019
skip_tags: true
skip_commits:
  message: /^init/
clone_depth: 1
environment:
  BUILD_TYPE: BETA
  ARCHIVE: 7z
platform:
  - x64
  - x86
branches:
  except:
    - master
    - development
    - ci-test
install:
  - cmd: dotnet --version
  - cmd: choco install dotnetcore-sdk
  - cmd: dotnet --version
  - ps: Install-Product node 12.18.3
  - cmd: npm -g install npm@6.14.8
  - cmd: npm install
before_build:
  - cmd: git submodule init
  - cmd: git submodule update
  - ps: .\Build\make-buildtools.ps1
build_script:
  - cmd: npm run document-build && robocopy /MIR /PURGE /R:3 /S "Source/Documents/build" "Source\Pe\Pe.Main\doc\help"
  - ps: .\Build\build.ps1 -ProductMode -IgnoreChanged -BuildType $env:BUILD_TYPE -Platforms $env:PLATFORM
  - ps: .\Build\compress.ps1 -Archive $env:ARCHIVE -Platforms $env:PLATFORM
before_test:
  - cmd: for /d %%f in (Source\Pe\*.Test) do ( cd %%f & nuget install Appveyor.TestLogger & cd ..\..\..\ )
test_script:
  - cmd: dotnet test Source/Pe/Pe.sln --verbosity normal --no-build --no-restore --configuration Release --runtime win-%PLATFORM% /p:Platform=%PLATFORM% /p:DefineConstants="%BUILD_TYPE%" --test-adapter-path:. --logger:Appveyor
artifacts:
  - path: Output\*.zip
  - path: Output\*.7z
  - path: Source\Documents\build
    name: document
cache:
  #- '%USERPROFILE%\.nuget\packages'
  - 'Source\Documents\node_modules'
  #- C:\ProgramData\chocolatey\bin -> appveyor.yml
  #- C:\ProgramData\chocolatey\lib -> appveyor.yml
