version: '{build}'
image: Visual Studio 2019
skip_tags: true
clone_depth: 1
environment:
  BUILD_TYPE:
  ARCHIVE: 7z
  MINIMUM_VERSION: 0.91.0
branches:
  only:
    - master
    - ci-test
install:
  - cmd: dotnet --version
  - cmd: choco install dotnetcore-sdk
  - cmd: dotnet --version
  - ps: Install-Product node 12.18.3
  - cmd: npm -g install npm@6.14.8
before_build:
  - cmd: git submodule init
  - cmd: git submodule update
  - ps: .\Build\make-buildtools.ps1
build_script:
  - ps: .\Build\create-document.ps1
  - ps: .\Build\build.ps1 -ProductMode -IgnoreChanged -BuildType $env:BUILD_TYPE -Platforms x64,x86
  - ps: .\Build\compress.ps1 -Diet -Archive $env:ARCHIVE -Platforms x64,x86
  - ps: .\Build\create-updateinfo.ps1 -TargetRepository bitbucket -MinimumVersion $env:MINIMUM_VERSION -ArchiveBaseUrl $env:PE_RELEASE_ARCHIVE_BASE_URL -NoteBaseUrl $env:PE_RELEASE_NOTE_BASE_URL -ReleaseDirectory Output -Archive $env:ARCHIVE -Platforms x64,x86
  - ps: .\Build\create-release-note.ps1
before_test:
  - cmd: for /d %%f in (Source\Pe\*.Test) do ( cd %%f & nuget install Appveyor.TestLogger & cd ..\..\..\ )
test_script:
  - cmd: dotnet test Source/Pe/Pe.sln --verbosity normal --no-build --no-restore --configuration Release --runtime win-x64 /p:Platform=x64 /p:DefineConstants="" --test-adapter-path:. --logger:Appveyor
  - cmd: dotnet test Source/Pe/Pe.sln --verbosity normal --no-build --no-restore --configuration Release --runtime win-x86 /p:Platform=x86 /p:DefineConstants="" --test-adapter-path:. --logger:Appveyor
artifacts:
  - path: Output\*.json
  - path: Output\*.html
  - path: Source\Documents\build
    name: document
deploy_script:
  - ps: .\Build\deploy.ps1 -TargetDownloader bitbucket -TargetRepository bitbucket -Archive $env:ARCHIVE -DeployApiDownloadUrl $env:PE_API_DOWNLOAD_URL -DeployApiTagUrl $env:PE_API_TAG_URL -DeployAccount $env:PE_RELEASE_ACCOUNT -DeployPassword $env:PE_RELEASE_PASSWORD

