version: '{build}'
image: Visual Studio 2019
skip_tags: true
clone_depth: 1
environment:
  BUILD_TYPE: BETA
  ARCHIVE: 7z
  MINIMUM_VERSION: 0.91.0
branches:
  only:
    - development
install:
  - cmd: dotnet --version
  #- cmd: choco install dotnetcore-sdk --version 3.1.100
  #- cmd: dotnet --version
  - ps: Install-Product node 12.14.1
  - cmd: npm --version
  #- cmd: npm -g install npm@6.13.4
before_build:
  - cmd: git submodule init
  - cmd: git submodule update
  - ps: .\Build\make-buildtools.ps1
build_script:
  - ps: .\Build\build.ps1 -ProductMode -IgnoreChanged -BuildType $env:BUILD_TYPE -Platforms x64,x86
  - ps: .\Build\create-document.ps1 -Platforms x64,x86
  - ps: .\Build\compress.ps1 -Diet -Archive $env:ARCHIVE -Platforms x64,x86
  - ps: .\Build\create-updateinfo.ps1 -TargetRepository bitbucket -MinimumVersion $env:MINIMUM_VERSION -ArchiveBaseUrl https://example.com -NoteBaseUrl https://example.net -ReleaseDirectory Output -Archive $env:ARCHIVE -Platforms x64,x86
  - ps: .\Build\create-release-note.ps1
before_test:
  - cmd: for /d %%f in (Source\Pe\*.Test) do ( cd %%f & nuget install Appveyor.TestLogger -Version 2.0.0 & cd ..\..\..\ )
test_script:
  - cmd: dotnet test Source/Pe/Pe.sln --verbosity normal --no-build --no-restore --configuration Release --runtime win-x64 /p:Platform=x64 /p:DefineConstants="" --test-adapter-path:. --logger:Appveyor
  - cmd: dotnet test Source/Pe/Pe.sln --verbosity normal --no-build --no-restore --configuration Release --runtime win-x86 /p:Platform=x86 /p:DefineConstants="" --test-adapter-path:. --logger:Appveyor
artifacts:
  - path: Output\*.zip
  - path: Output\*.7z
  - path: Output\*.json
  - path: Output\*.html
  - path: Source\Documents\build
    name: document

