#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    - develop
    - rc-0.33.0

#---------------------------------#
#    environment configuration    #
#---------------------------------#

skip_tags: true

os: Windows Server 2012

# setting up etc\hosts file
hosts:
  queue-server: 127.0.0.1
  db.server.com: 127.0.0.2

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: false

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  project: Pe\Pe.sln      # path to Visual Studio solution or project
  # MSBuild verbosity level
  verbosity: quiet|minimal|normal|detailed

before_build:
  cd Pe
  nuget restore
  cd ..\

