version: '{build}'
image: Visual Studio 2019
skip_tags: true
clone_depth: 1
environment:
  CI: HAGE
  BUILD_TYPE: BETA
  BUILD_OUTPUT: FULL
platform:
  - x64
  - x86
branches:
  except:
    - master
install:
  - cmd: dotnet --version
  - cmd: choco install dotnetcore-sdk --version 3.0.100
  - cmd: dotnet --version
before_build:
  - cmd: git submodule init
  - cmd: git submodule update
build_script:
  - cmd: dotnet build   Source/Pe/Pe.sln       --verbosity normal --configuration Release --runtime win-%PLATFORM% /p:Platform=%PLATFORM% /p:DefineConstants="%BUILD_TYPE%"
  - cmd: dotnet publish Source/Pe/Pe/Pe.csproj --verbosity normal --configuration Release --runtime win-%PLATFORM% /p:Platform=%PLATFORM% /p:DefineConstants="%BUILD_TYPE%" --output Output/Release/%PLATFORM%/Pe --self-contained true
before_test:
  - cmd: for /d %%f in (Source\Pe\*.Test) do ( cd %%f & nuget install Appveyor.TestLogger -Version 2.0.0 & cd ..\..\..\ )
test_script:
  - cmd: dotnet test Source/Pe/Pe.sln --verbosity normal --no-build --no-restore --configuration Release --runtime win-%PLATFORM% /p:Platform=%PLATFORM% /p:DefineConstants="%BUILD_TYPE%" --test-adapter-path:. --logger:Appveyor
artifacts:
- path: Output\Release\%PLATFORM%
cache:
 - '%LOCALAPPDATA%\NuGet'
 - '%USERPROFILE%\.nuget'
 - C:\ProgramData\chocolatey\bin -> appveyor.yml
 - C:\ProgramData\chocolatey\lib -> appveyor.yml
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  informational_version: '%APPVEYOR_REPO_COMMIT%'
