version: '{build}'
skip_tags: true
clone_depth: 1
cache: Source\Pe\packages
before_build:
  - cmd: git submodule init
  - cmd: git submodule update
  - cmd: dotnet --version
  - cmd: dotnet restore Source/Pe/Pe.sln --verbosity m
build_script:
  - cmd: dotnet build Source/Pe/Pe.sln --configuration Release --runtime win-x64 --verbosity normal
test_script:
  - cmd: dotnet test Source/Pe/Pe.sln --configuration Release --runtime win-x64 --verbosity normal
artifacts:
- path: Output\
