version: '{build}'
image: Visual Studio 2019
skip_tags: true
skip_commits:
  message: /^init/
clone_depth: 1
environment:
  BUILD_TYPE: BETA
  ARCHIVE: 7z
  MINIMUM_VERSION: 0.00.0
  NUGET_PACKAGES: C:\nuget
platform:
  - x64
  - x86
branches:
  except:
    - master
    - development
    - ci-test
install:
  - cmd: dotnet --version
  #- cmd: choco install dotnetcore-sdk
  #- cmd: dotnet --version
  - ps: Install-Product node 15.6.0
  - cmd: npm -g install npm@7.4.0
  - cmd: npm install
before_build:
  - cmd: git submodule init
  - cmd: git submodule update
  - ps: .\Build\make-buildtools.ps1
build_script:
  - cmd: npm run help-ci
  - ps: .\Build\build.ps1 -ProductMode -IgnoreChanged -BuildType $env:BUILD_TYPE -Platforms $env:PLATFORM
  - ps: .\Build\build.ps1 -IgnoreChanged -BuildType $env:BUILD_TYPE -Platforms $env:PLATFORM
before_test:
  - cmd: for /d %%f in (Source\Pe\*.Test) do ( cd %%f & nuget install Appveyor.TestLogger & cd ..\..\..\ )
test_script:
  - cmd: dotnet test Source/Pe/Pe.sln --verbosity normal --no-build --no-restore --configuration Release --runtime win-%PLATFORM% /p:Platform=%PLATFORM% /p:DefineConstants="%BUILD_TYPE%" --test-adapter-path:. --logger:Appveyor
  - cmd: VSTest.Console Source\Pe.Boot\Pe.Boot.Test\bin\Release\%PLATFORM%\Pe.Boot.Test.dll /InIsolation /Platform:%PLATFORM% /Logger:Appveyor
  - cmd: VSTest.Console Source\Pe.Boot\Pe.Boot.Test\bin\CI_TEST\%PLATFORM%\Pe.Boot.Test.dll /InIsolation /Platform:%PLATFORM% /Logger:Appveyor
after_test:
  - ps: .\Build\compress.ps1 -Archive $env:ARCHIVE -Platforms $env:PLATFORM
  - ps: .\Build\create-updateinfo.ps1 -TargetRepository bitbucket -MinimumVersion $env:MINIMUM_VERSION -ArchiveBaseUrl https://example.com -NoteBaseUrl https://example.net -ReleaseDirectory Output -Archive $env:ARCHIVE -Platforms $env:PLATFORM
  - ps: .\Build\create-release-note.ps1
artifacts:
  - path: Output\*.zip
  - path: Output\*.7z
  - path: Output\*.json
  - path: Output\*.html
  - path: Output\help
    name: document
cache:
  #- '%USERPROFILE%\.nuget\packages'
  - 'node_modules'
  #- C:\ProgramData\chocolatey\bin -> appveyor.yml
  #- C:\ProgramData\chocolatey\lib -> appveyor.yml
  - 'C:\nuget'
