version: '{build}'
image: Visual Studio 2019
skip_tags: true
clone_depth: 1
environment:
  CI: HAGE
  BUILD_TYPE: BETA
  BUILD_OUTPUT: FULL
platform:
  - x64
  - x86
branches:
  only:
    - pipeline
install:
  - cmd: dotnet --version
  #- cmd: choco install dotnetcore-sdk --version 3.1.100
  #- cmd: dotnet --version
  - cmd: set
before_build:
  - cmd: git submodule init
  - cmd: git submodule update
build_script:
  - ps: .\Build\build.ps1 -platform $env:PLATFORM -buildType $env:BUILD_TYPE
  - ps: .\Build\compress.ps1 -SourceDirectory Output\Release\$env:PLATFORM\Pe -DestinationDirectory Output -Platform $env:PLATFORM
before_test:
  - cmd: for /d %%f in (Source\Pe\*.Test) do ( cd %%f & nuget install Appveyor.TestLogger -Version 2.0.0 & cd ..\..\..\ )
test_script:
  - cmd: dotnet test Source/Pe/Pe.sln --verbosity normal --no-build --no-restore --configuration Release --runtime win-%PLATFORM% /p:Platform=%PLATFORM% /p:DefineConstants="%BUILD_TYPE%" --test-adapter-path:. --logger:Appveyor
artifacts:
- path: Output\*.zip
cache:
 - '%LOCALAPPDATA%\NuGet'
 - '%USERPROFILE%\.nuget'
 - C:\ProgramData\chocolatey\bin -> appveyor.yml
 - C:\ProgramData\chocolatey\lib -> appveyor.yml
