version: '{build}'
image: Visual Studio 2019
skip_tags: true
clone_depth: 1
environment:
  BUILD_TYPE:
  ARCHIVE: 7z
  MINIMUM_VERSION: 0.91.0
branches:
  only:
    - master
    - ci-test
install:
  - cmd: dotnet --version
  #- cmd: choco install dotnetcore-sdk
  #- cmd: dotnet --version
  - ps: Install-Product node 15.6.0
  - cmd: npm -g install npm@7.4.0
  - cmd: npm install
before_build:
  - cmd: git submodule init
  - cmd: git submodule update
  - ps: .\Build\make-buildtools.ps1
build_script:
  - cmd: npm run help-ci
  - ps: .\Build\build.ps1 -ProductMode -IgnoreChanged -BuildType $env:BUILD_TYPE -Platforms x64,x86
before_test:
  - cmd: for /d %%d in (Source\Pe\*.Test) do ( cd %%d & nuget install Appveyor.TestLogger & cd ..\..\..\ )
test_script:
  - ps: .\Build\test.ps1 -MainConfigurations Release -BootConfigurations Release,CI_TEST -Logger Appveyor -Platforms x64,x86
after_test:
  - ps: .\Build\compress.ps1 -Diet -Archive $env:ARCHIVE -Platforms x64,x86
  - ps: .\Build\create-updateinfo.ps1 -TargetRepository bitbucket -MinimumVersion $env:MINIMUM_VERSION -ArchiveBaseUrl $env:PE_RELEASE_ARCHIVE_BASE_URL -NoteBaseUrl $env:PE_RELEASE_NOTE_BASE_URL -ReleaseDirectory Output -Archive $env:ARCHIVE -Platforms x64,x86
  - ps: .\Build\create-release-note.ps1
artifacts:
  - path: Output\*.json
  - path: Output\*.html
  - path: Output\help
    name: document
deploy_script:
  - ps: .\Build\deploy.ps1 -TargetDownloader bitbucket -TargetRepository bitbucket -Archive $env:ARCHIVE -DeployApiDownloadUrl $env:PE_API_DOWNLOAD_URL -DeployApiTagUrl $env:PE_API_TAG_URL -DeployAccount $env:PE_RELEASE_ACCOUNT -DeployPassword $env:PE_RELEASE_PASSWORD

