image: microsoft/dotnet:sdk
pipelines:
  branches:
    pipeline:
      - step:
          script:
           - dotnet --version
           - git submodule init
           - git submodule update
