using System;
using System.Collections.Generic;
using System.Text;

namespace ContentTypeTextNet.Pe.Generator.Id
{
    public class SourceBuilder
    {
        #region property

        public string Header => "// <auto-generated/>";

        #endregion

        #region function

        public string ToCode<T>(T target)
            where T : Enum
        {
            var type = target.GetType();
            return "global::" + type.FullName + "." + target.ToString();
        }

        public string ToCode<T>()
        {
            var type = typeof(T);
            return "global::" + type.FullName;
        }

        #endregion
    }
}
