using System;
using System.Collections.Generic;
using System.Text;

namespace ContentTypeTextNet.Pe.Generator.Id
{
    public class SourceBuilder
    {
        #region function

        public string ToHeader()
        {
            return "// <auto-generated/>\r\n\r\n";
        }

        public string ToCode<T>(T target)
            where T : Enum
        {
            var type = target.GetType();
            return "global::" + type.FullName + "." + target.ToString();
        }

        public string ToCode<T>()
            where T : class
        {
            var type = typeof(T);
            return "global::" + type.FullName;
        }

        #endregion
    }
}
