name: Build

on: push

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: <Add> msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: <Embedded> git revision
        shell: pwsh
        run: .\Build\embedded-revision.ps1 -InformationAction Continue -Revision ${{ github.sha }} -ProjectFilePath .\Source\Directory.Build.props

      - name: <Build> Plugin
        shell: pwsh
        run: .\FullBuild.ps1 -InformationAction Continue

      - name: <Artifact> Plugin
        uses: actions/upload-artifact@v4
        with:
          name: Plugin
          path: |
            Output\*.zip
            Output\update-*.json
          if-no-files-found: error

  test:

    runs-on: windows-latest

    steps:

      - name: <Checkout> Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: <Add> msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: <Test> Plugin
        shell: pwsh
        run: .\FullTest.ps1 -InformationAction Continue

  deploy:
    needs:
      - build
      - test

    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/ci-test'

    runs-on: ubuntu-latest

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v4

      - name: <Download> Application
        uses: actions/download-artifact@v4
        with:
          name: Plugin
          path: Output

      - name: <Add> get-net-sdk-project-versions-action
        uses: kzrnm/get-net-sdk-project-versions-action@v1
        id: version
        with:
          proj-path: Source/Directory.Build.props

      - name: <Delete> TEST Tag
        if: github.ref == 'refs/heads/ci-test'
        continue-on-error: true
        uses: ClementTsang/delete-tag-and-release@v0.4.0
        with:
          delete_release: true
          tag_name: ${{ steps.version.outputs.dot }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: <Create> Release
        uses: actions/github-script@v7
        with:
          script: |
            const releaseId = await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{steps.version.outputs.version}}",
              sha: context.sha
            })

      - name: <Upload> Plugin
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Output/*
          file_glob: true
          tag: ${{steps.version.outputs.version}}



