<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Pe.Bridge.Test</AssemblyName>
    <RootNamespace>ContentTypeTextNet.Pe.Bridge.Test</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pe.Bridge\Pe.Bridge.csproj" />
  </ItemGroup>


</Project>
