<Project Sdk="MSTest.Sdk/4.1.0">
  <PropertyGroup>
    <AssemblyName>Pe.Bridge.Test</AssemblyName>
    <RootNamespace>ContentTypeTextNet.Pe.Bridge.Test</RootNamespace>

    <!--<IsTestProject>true</IsTestProject>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>-->
  </PropertyGroup>

<PropertyGroup>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>

    <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>

    <OutputType>Exe</OutputType>

    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Platform.MSBuild" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pe.Bridge\Pe.Bridge.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage">
      <VersionOverride>18.11.2</VersionOverride>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.TrxReport">
      <VersionOverride>2.4.1</VersionOverride>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="MSTest.TestAdapter">
      <VersionOverride>4.4.1</VersionOverride>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="MSTest.TestFramework">
      <VersionOverride>4.4.1</VersionOverride>
    </PackageReference>
  </ItemGroup>
</Project>
