version: '{build}'
image: Visual Studio 2019
skip_tags: true
clone_depth: 1
platform:
  - x64
  - x86
before_build:
  - cmd: dotnet --version
  - cmd: choco install dotnetcore-sdk --version 3.0.100-preview9-014004
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build Source/Pe.Bridge.sln --verbosity normal --configuration Release --runtime win-%PLATFORM% /p:Platform=%PLATFORM%
before_test:
  - cmd: for /d %%f in (Source\*.Test) do ( cd %%f & nuget install Appveyor.TestLogger -Version 2.0.0 & cd ..\..\ )
test_script:
  - cmd: dotnet test Source/Pe.Bridge.sln --verbosity normal --no-build --configuration Release --runtime win-%PLATFORM%  --test-adapter-path:. --logger:Appveyor
cache:
 - '%LOCALAPPDATA%\NuGet'
 - '%USERPROFILE%\.nuget'
 - C:\ProgramData\chocolatey\bin -> appveyor.yml
 - C:\ProgramData\chocolatey\lib -> appveyor.yml

