using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ContentTypeTextNet.Pe.Library.ObjectProxy
{
    [Generator(LanguageNames.CSharp)]
    public partial class ObjectProxyGenerator: IIncrementalGenerator
    {
        #region define

        #endregion

        #region function


        //[System.Diagnostics.CodeAnalysis.SuppressMessage("MicrosoftCodeAnalysisCorrectness", "RS1035:アナライザーに対して禁止された API を使用しない", Justification = "<保留中>")]
        //private void GenerateSource(IncrementalGeneratorPostInitializationContext context)
        //{
        //    var baseNamespace = "ContentTypeTextNet.Pe.Library.CliProxy";
        //    var targetDefines = new[] {
        //        //typeof(System.Environment),
        //        typeof(System.IO.File),
        //        //typeof(System.IO.Directory),
        //    };

        //    foreach(var targetDefine in targetDefines) {
        //        context.CancellationToken.ThrowIfCancellationRequested();

        //        var source = new SourceWriter();
        //        var typeGenerator = new TypeGenerator(source, targetDefine, baseNamespace, targetDefine.FullName + ".g.cs");

        //        source.Append("// <auto-generated />");
        //        source.AppendEmptyLine();

        //        source.Append(typeGenerator.CreateUsingStatement());
        //        source.AppendEmptyLine();

        //        source.AppendLine(typeGenerator.CreateNamespaceStatement());
        //        source.AppendEmptyLine();

        //        // インターフェイス
        //        source.AppendLine(typeGenerator.CreateInterfaceStatement());
        //        source.AppendEmptyLine();

        //        // インターフェイスに対する直接クラス
        //        source.AppendLine(typeGenerator.CreateImplementStatement(true));
        //        source.AppendEmptyLine();

        //        var code = source.ToString();
        //        context.AddSource(
        //            hintName: typeGenerator.FilePath,
        //            source: source.ToString()
        //        );
        //    }
        //}

        private void RegisterSource(SourceProductionContext sourceContext, GeneratorAttributeSyntaxContext syntaxContext)
        {
            sourceContext.CancellationToken.ThrowIfCancellationRequested();

            var symbol = (INamedTypeSymbol)syntaxContext.TargetSymbol;
            var node = (TypeDeclarationSyntax)syntaxContext.TargetNode;

            var sourceWriter = new SourceWriter();
            var typeGenerator = new TypeGenerator(sourceWriter, symbol, node);

            sourceWriter.Append("// <auto-generated />");
            sourceWriter.AppendEmptyLine();

            sourceWriter.Append(typeGenerator.CreateUsingStatement());
            sourceWriter.AppendEmptyLine();

            sourceWriter.AppendLine(typeGenerator.CreateNamespaceStatement());
            sourceWriter.AppendEmptyLine();

            // インターフェイス
            sourceWriter.AppendLine(typeGenerator.CreateInterfaceStatement());
            sourceWriter.AppendEmptyLine();

            // インターフェイスに対する直接クラス
            sourceWriter.AppendLine(typeGenerator.CreateImplementStatement(true));
            sourceWriter.AppendEmptyLine();

            var code = sourceWriter.ToString();
            sourceContext.AddSource(
                hintName: typeGenerator.SourceFilePath,
                source: code
            );
        }

        #endregion

        #region IIncrementalGenerator

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            //context.RegisterPostInitializationOutput(GenerateSource);
            context.RegisterPostInitializationOutput(context => {
                context.AddSource($"{SourceHelper.AttributeClassName}.g.cs", $$"""
namespace {{SourceHelper.AttributeNamespace}};

using System;

[AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
public sealed class {{SourceHelper.AttributeClassName}} : Attribute
{
    public {{SourceHelper.AttributeClassName}}(Type targetType)
    {
        TargetType = targetType;
    }

    #region property

    public Type TargetType { get; }

    #endregion
}
""");
            });

            var source = context.SyntaxProvider.ForAttributeWithMetadataName(
                $"{SourceHelper.AttributeNamespace}.{SourceHelper.AttributeClassName}",
                static (node, token) => true,
                static (context, token) => context
            );

            context.RegisterSourceOutput(source, RegisterSource);
        }



        #endregion
    }
}


