name: Build Works

on:
  push:
    branches-ignore:
      - master
      - ci-test
      - development
  pull_request:
    branches-ignore:
      - master
      - ci-test
      - development

env:
  MAIN_ARCHIVE: tar
  DEFAULT_ARCHIVE: 7z
  MINIMUM_VERSION: 0.91.0
  PE_RELEASE_ARCHIVE_BASE_URL: https://example.com
  PE_RELEASE_NOTE_BASE_URL: https://example.com

jobs:
  matrix-build:

    strategy:
      matrix:
        PLATFORM: ["x86", "x64"]

    runs-on: windows-latest

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v3

      - name: <Add> msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: <Add> VSTest
        uses: darenm/Setup-VSTest@v1

      - name: <Add> Node/NPM
        uses: actions/setup-node@v3
        with:
          node-version: 15.14.0
          cache: npm

      - name: <Cache> Nuget
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: <Show> Tools
        run: |
          dotnet --version
          pwsh --version
          7z -version
          exit 0

      - name: <Generate> Data
        shell: pwsh
        run: .\Build\generate-data-files.ps1

      - name: <Install> NPM
        run: npm install

      - name: <Build> BuildTools
        shell: pwsh
        run: .\Build\make-buildtools.ps1

      - name: <Build> Document
        run: npm run help-ci

      - name: <Artifact> Document
        uses: actions/upload-artifact@v3
        with:
          name: Document
          path: Output\help

      - name: <Build> Application
        shell: pwsh
        run: .\Build\build.ps1 -ProductMode -IgnoreChanged -BuildType BETA -Platforms ${{ matrix.PLATFORM }}

      - name: <Test> Application
        shell: pwsh
        run: .\Build\test.ps1 -MainConfigurations Release -BootConfigurations Release,CI_TEST -Platforms ${{ matrix.PLATFORM }}

      - name: <Archive> Application
        shell: pwsh
        run: .\Build\compress.ps1 -MainArchive ${{ env.MAIN_ARCHIVE }} -DefaultArchive ${{ env.DEFAULT_ARCHIVE }} -Platforms ${{ matrix.PLATFORM }}

      - name: <Make> update info
        shell: pwsh
        run: .\Build\create-updateinfo.ps1 -TargetRepository github -MinimumVersion ${{ env.MINIMUM_VERSION }} -ArchiveBaseUrl ${{ env.PE_RELEASE_ARCHIVE_BASE_URL }} -NoteBaseUrl ${{ env.PE_RELEASE_NOTE_BASE_URL }} -ReleaseDirectory Output -MainArchive ${{ env.MAIN_ARCHIVE }} -DefaultArchive ${{ env.DEFAULT_ARCHIVE }} -Platforms ${{ matrix.PLATFORM }}

      - name: <Make> release note
        shell: pwsh
        run: .\Build\create-release-note.ps1

      - name: <Artifact> Application
        uses: actions/upload-artifact@v3
        with:
          name: Pe-${{ matrix.PLATFORM }}
          path: |
            Output\Pe_*.${{ env.MAIN_ARCHIVE }}
            Output\Pe_*.html
            Output\Pe_*.md
            Output\*-tag.json
            Output\update.json
            Output\gen-*

      - name: <Artifact> Pe.Plugins.Reference
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugins.Reference-${{ matrix.PLATFORM }}
          path: |
            Output\Pe.Plugins.Reference.*_${{ matrix.PLATFORM }}.${{ env.DEFAULT_ARCHIVE }}
            Output\Pe.Plugins.Reference.*.html
            Output\update-Pe.Plugins.Reference.*.json

