name: Build Release

on:
  push:
    branches:
    - master
    - ci-test
    - develop

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_build-template.yml
    with:
      MAIN_ARCHIVE: 7z
      DEFAULT_ARCHIVE: 7z
      PE_RELEASE_ARCHIVE_BASE_URL: https://example.com
      PE_RELEASE_NOTE_BASE_URL: https://example.com

  tree:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: <Download> Release Note
        uses: actions/download-artifact@v3
        with:
          name: History
          path: artifacts/history

      - name: <Download> Plugins x86
        uses: actions/download-artifact@v3
        with:
          name: Pe.Plugins.Reference_x86
          path: artifacts/Pe.Plugins.Reference

      - name: <Download> Plugins x64
        uses: actions/download-artifact@v3
        with:
          name: Pe.Plugins.Reference_x64
          path: artifacts/Pe.Plugins.Reference

      - name: <Download> Application x86
        uses: actions/download-artifact@v3
        with:
          name: Pe_x86
          path: artifacts/Pe

      - name: <Download> Application x64
        uses: actions/download-artifact@v3
        with:
          name: Pe_x64
          path: artifacts/Pe

      - name: <Download> Plugins Information
        uses: actions/download-artifact@v3
        with:
          name: Information_Pe.Plugins.Reference
          path: artifacts/info/plugins

      - name: <Download> Application Information
        uses: actions/download-artifact@v3
        with:
          name: Information_Pe
          path: artifacts/info/pe

      - name: <🌳> 🌲
        shell: pwsh
        run:  |
          Get-ChildItem artifacts -R -File | Select-Object FullName | Format-Table -AutoSize -Wrap
