name: Build WORKS

on:
  - push
  - pull_request

env:
  BUILD_TYPE: BETA
  MAIN_ARCHIVE: tar
  DEFAULT_ARCHIVE: 7z
  MINIMUM_VERSION: 0.00.0

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Node/NPM
        uses: actions/setup-node@v3
        with:
          node-version: 15.14.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: tools
        run: |
          dotnet --version
          pwsh --version
          dir
          tree

      - name: Build BuildTools
        shell: pwsh
        run: ./Build/make-buildtools.ps1

    # - uses: actions/checkout@v3
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v2
    #   with:
    #     dotnet-version: 6.0.x
    # - name: Restore dependencies
    #   run: dotnet restore
    # - name: Build
    #   run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
