name: Build WORKS

on:
  - push
  - pull_request

env:
  BUILD_TYPE: BETA
  MAIN_ARCHIVE: tar
  DEFAULT_ARCHIVE: 7z
  MINIMUM_VERSION: 0.00.0

jobs:
  matrix-build:

    strategy:
      matrix:
        PLATFORM: ["x86", "x64"]

    runs-on: windows-latest

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v3

      - name: <Add> msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: <Add> Node/NPM
        uses: actions/setup-node@v3
        with:
          node-version: 15.14.0
          cache: npm

      - name: <Add> VSTest
        uses: darenm/Setup-VSTest@v1

      - name: <Cache> Nuget
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: <Show> Tools
        run: |
          dotnet --version
          pwsh --version
          7z -version
          exit 0

      - name: <Install> NPM
        run: npm install

      - name: <Build> BuildTools
        shell: pwsh
        run: .\Build\make-buildtools.ps1

      - name: <Build> Document
        run: npm run help-ci

      - name: <Artifact> Document
        uses: actions/upload-artifact@v3
        with:
          name: Document
          path: Output\help

      - name: <Build> Application
        shell: pwsh
        run: .\Build\build.ps1 -ProductMode -IgnoreChanged -BuildType ${{ env.BUILD_TYPE }} -Platforms ${{ matrix.PLATFORM }}

      - name: <Test> Application
        shell: pwsh
        run: .\Build\test.ps1 -MainConfigurations Release -BootConfigurations Release,CI_TEST -Platforms ${{ matrix.PLATFORM }}

      - name: <Archive> Application
        shell: pwsh
        run: .\Build\compress.ps1 -MainArchive ${{ env.MAIN_ARCHIVE }} -DefaultArchive ${{ env.DEFAULT_ARCHIVE }} -Platforms ${{ matrix.PLATFORM }}

      - name: <Artifact> Pe
        uses: actions/upload-artifact@v3
        with:
          name: Pe-${{ matrix.PLATFORM }}
          path: Output\Pe_*.${{ env.MAIN_ARCHIVE }}

      #region artifact.bat
      - name: <Artifact> Pe.Plugins.DefaultTheme
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugins.DefaultTheme-${{ matrix.PLATFORM }}
          path: Output\Pe.Plugins.DefaultTheme_*.${{ env.DEFAULT_ARCHIVE }}
      - name: <Artifact> Pe.Plugins.Reference.ClassicTheme
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugins.Reference.ClassicTheme-${{ matrix.PLATFORM }}
          path: Output\Pe.Plugins.Reference.ClassicTheme_*.${{ env.DEFAULT_ARCHIVE }}
      - name: <Artifact> Pe.Plugins.Reference.Clock
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugins.Reference.Clock-${{ matrix.PLATFORM }}
          path: Output\Pe.Plugins.Reference.Clock_*.${{ env.DEFAULT_ARCHIVE }}
      - name: <Artifact> Pe.Plugins.Reference.Eyes
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugins.Reference.Eyes-${{ matrix.PLATFORM }}
          path: Output\Pe.Plugins.Reference.Eyes_*.${{ env.DEFAULT_ARCHIVE }}
      - name: <Artifact> Pe.Plugins.Reference.FileFinder
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugins.Reference.FileFinder-${{ matrix.PLATFORM }}
          path: Output\Pe.Plugins.Reference.FileFinder_*.${{ env.DEFAULT_ARCHIVE }}
      - name: <Artifact> Pe.Plugins.Reference.Html
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugins.Reference.Html-${{ matrix.PLATFORM }}
          path: Output\Pe.Plugins.Reference.Html_*.${{ env.DEFAULT_ARCHIVE }}
      #endregion


      - name: <Artifact> Pe.Plugins.Reference.Html
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugins.Reference.Html-${{ matrix.PLATFORM }}
          path: Output\Pe.Plugins.Reference.Html_*.${{ env.DEFAULT_ARCHIVE }}
      - name: <Artifact> Pe.Plugins.Reference.Html
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugins.Reference.Html-${{ matrix.PLATFORM }}
          path: Output\Pe.Plugins.Reference.Html_*.${{ env.DEFAULT_ARCHIVE }}
      - name: <Artifact> Pe.Plugins.Reference.Html
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugins.Reference.Html-${{ matrix.PLATFORM }}
          path: Output\Pe.Plugins.Reference.Html_*.${{ env.DEFAULT_ARCHIVE }}
      - name: <Artifact> Pe.Plugins.Reference.Html
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugins.Reference.Html-${{ matrix.PLATFORM }}
          path: Output\Pe.Plugins.Reference.Html_*.${{ env.DEFAULT_ARCHIVE }}
      - name: <Artifact> Pe.Plugins.Reference.Html
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugins.Reference.Html-${{ matrix.PLATFORM }}
          path: Output\Pe.Plugins.Reference.Html_*.${{ env.DEFAULT_ARCHIVE }}
      - name: <Artifact> Pe.Plugins.Reference.Html
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugins.Reference.Html-${{ matrix.PLATFORM }}
          path: Output\Pe.Plugins.Reference.Html_*.${{ env.DEFAULT_ARCHIVE }}
      #endregion

      - name: <Artifact> Pe.Plugin.Reference-${{ matrix.PLATFORM }}.html
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugin.Reference-${{ matrix.PLATFORM }}
          path: Output\Pe.Plugin.Reference.HTML

      - name: <Artifact> update-*.html
        uses: actions/upload-artifact@v3
        with:
          name: update
          path: Output\Pe_*.html

      - name: <Artifact> update-*.json
        uses: actions/upload-artifact@v3
        with:
          name: update
          path: Output\update.json


