name: Build WORKS

on:
  - push
  - pull_request

env:
  BUILD_TYPE: BETA
  MAIN_ARCHIVE: tar
  DEFAULT_ARCHIVE: 7z
  MINIMUM_VERSION: 0.00.0

jobs:
  matrix-build:

    strategy:
      matrix:
        PLATFORM: ["x86", "x64"]

    runs-on: windows-latest

    steps:
      - name: [Add] msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: [Add] Node/NPM
        uses: actions/setup-node@v3
        with:
          node-version: 15.14.0

      - name: [Checkout] Repository
        uses: actions/checkout@v3

      - name: [Show] Tools
        run: |
          dotnet --version
          pwsh --version

      - name: Install NPM
        run: npm install

      - name: [Build] BuildTools
        shell: pwsh
        run: .\Build\make-buildtools.ps1

      - name: [Build] Document
        run: npm run help-ci

      - name: [Artifact] Document
        uses: actions/upload-artifact@v3
        with:
          name: Document
          path: Output\help

      - name: [Build] Application
        shell: pwsh
        run: .\Build\build.ps1 -ProductMode -IgnoreChanged -BuildType ${{ env.BUILD_TYPE }} -Platforms ${{ matrix.PLATFORM }}

    # - uses: actions/checkout@v3
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v2
    #   with:
    #     dotnet-version: 6.0.x
    # - name: Restore dependencies
    #   run: dotnet restore
    # - name: Build
    #   run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
