name: Build Development

on:
  push:
    branches:
    - master
    - ci-test
    - development

env:
  BUILD_TYPE: BETA
  MAIN_ARCHIVE: 7z
  DEFAULT_ARCHIVE: 7z
  MINIMUM_VERSION: 0.91.0

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v3

      - name: <Add> msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: <Add> VSTest
        uses: darenm/Setup-VSTest@v1

      - name: <Add> Node/NPM
        uses: actions/setup-node@v3
        with:
          node-version: 15.14.0

      - name: <Show> Tools
        run: |
          dotnet --version
          pwsh --version
          7z -version
          exit 0

      - name: <Install> NPM
        run: npm install

      - name: <Build> BuildTools
        shell: pwsh
        run: .\Build\make-buildtools.ps1

      - name: <Build> Document
        run: npm run help-ci

      - name: <Artifact> Document
        uses: actions/upload-artifact@v3
        with:
          name: Document
          path: Output\help

      - name: <Build> Application
        shell: pwsh
        run: .\Build\build.ps1 -ProductMode -IgnoreChanged -BuildType ${{ env.BUILD_TYPE }} -Platforms x86,x64

      - name: <Test> Application
        shell: pwsh
        run: .\Build\test.ps1 -MainConfigurations Release -BootConfigurations Release,CI_TEST -Platforms x86,x64

      - name: <Archive> Application
        shell: pwsh
        run: .\Build\compress.ps1 -MainArchive ${{ env.MAIN_ARCHIVE }} -DefaultArchive ${{ env.DEFAULT_ARCHIVE }} -Platforms x86,x64

      - name: <Make> update info
        shell: pwsh
        run: .\Build\create-updateinfo.ps1 -TargetRepository github -MinimumVersion ${{ env.MINIMUM_VERSION }} -ArchiveBaseUrl https://example.com -NoteBaseUrl https://example.net -ReleaseDirectory Output -MainArchive ${{ env.MAIN_ARCHIVE }} -DefaultArchive ${{ env.DEFAULT_ARCHIVE }} -Platforms x86,x64

      - name: <Make> release note
        shell: pwsh
        run: .\Build\create-release-note.ps1

      - name: <Artifact> Application
        uses: actions/upload-artifact@v3
        with:
          name: Pe
          path: |
            Output\Pe_*.${{ env.MAIN_ARCHIVE }}
            Output\Pe_*.html
            Output\*-tag.json
            Output\update.json

      - name: <Artifact> Pe.Plugins.Reference
        uses: actions/upload-artifact@v3
        with:
          name: Pe.Plugins.Reference
          path: |
            Output\Pe.Plugins.Reference.*_*.${{ env.DEFAULT_ARCHIVE }}
            Output\Pe.Plugins.Reference.*.html
            Output\update-Pe.Plugins.Reference.*.json

  deploy:
    needs: build

    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/ci-test'

    runs-on: windows-latest

    steps:
      - name: <Download> Application
        uses: actions/download-artifact@v3
        with:
          name: Pe

      - name: <Download> Pe.Plugins.Reference
        uses: actions/download-artifact@v3
        with:
          name: Pe.Plugins.Reference

      - name: <Tag> set tag
        run: tree
