name: Build Development

on:
  push:
    branches:
    - master
    - ci-test
    - development

env:
  BUILD_TYPE: BETA
  MAIN_ARCHIVE: tar
  DEFAULT_ARCHIVE: 7z
  MINIMUM_VERSION: 0.91.0
  PE_RELEASE_ARCHIVE_BASE_URL: https://example.com
  PE_RELEASE_NOTE_BASE_URL: https://example.com

jobs:
  deploy:

    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/ci-test'

    runs-on: windows-latest

    steps:
      - name: <Checkout> Repository
        uses: actions/checkout@v3

      - name: <Generate> Data
        shell: pwsh
        run: .\Build\generate-data-files.ps1

      - name: <Read> gen-version
        id: version
        shell: pwsh
        run: |
          $content = (Get-Content Output/gen-version.txt)
          Write-Output "::set-output name=outputs::$content"

      - name: TEST
        run: echo ${{ steps.version.outputs.content }}

      # - name: <Create> Tag
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: "refs/tags/${{ steps.version.outputs.content }}",
      #         sha: context.sha
      #       })
